language: node_js

node_js:
  - "0.1"
  - "0.12"
  - "4"
  - "6"
  - "7"
  - "8"
  - "10"
  - "12"
  - "13"
  - "14"

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script: npm run test
    - script: npm run lint