language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - "14"

jobs:
  include:
    - stage: build
      name: "Typescript Build"
      script: npm run build
    - stage: test
      name: "Tests"
      script: npm run test
    - script: npm run lint
      name: "Linting"